compile :
	gcc t08_01.c academic.c -o t08_01
	gcc t08_02.c academic.c -o t08_02
	gcc t08_03.c academic.c -o t08_03
	gcc t08_04.c academic.c -o t08_04
	gcc t08_05.c academic.c -o t08_05

test_01 :
	./t08_01

test_02 :
	./t08_02

test_03 :
	./t08_03

test_04 :
	./t08_04

test_05 :
	./t08_05
